version: "3.5"

services:
  welbex_db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:5432
