version: "3.5"

services:
  welbex_db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:5432
